name: ${PROJECT_NAME}-prod
services:
  php:
    build:
      context: . # Trick to include both .env and symfony/ in the build context
      dockerfile: ./symfony/Dockerfile
      target: php-fpm
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'pidof php-fpm > /dev/null || exit 1']
      interval: 10s
      timeout: 5s
      retries: 3
    entrypoint: |
      /bin/bash -c "
        echo '🔄 Applying migrations...'
        php bin/console doctrine:migrations:migrate --no-interaction --allow-no-migration --all-or-nothing --query-time || exit 1
        echo '🚀 Starting PHP-FPM...'
        exec php-fpm
      "

  nginx:
    image: nginx:latest
    volumes:
      - ./symfony/nginx.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    depends_on:
      php:
        condition: service_healthy
    ports:
      - 8000:8000

  mysql:
    restart: unless-stopped

  phpmyadmin:
    restart: unless-stopped

volumes:
  mysql-data:
    name: '${PROJECT_NAME}-prod-db'
