services:
  symfony:
    build:
      context: ./symfony
      args:
        PHP_VERSION: ${PHP_VERSION}
      target: php-symfony
    environment: # Vars used both by Docker and Symfony
      APP_ENV: ${APP_ENV}
      PROJECT_NAME: ${PROJECT_NAME}
      MYSQL_VERSION: ${MYSQL_VERSION}
      DATABASE_ADMIN_PASSWORD: ${DATABASE_ADMIN_PASSWORD}
    volumes:
      - ./:/var/www/
      - symfony-var:/var/www/symfony/var
      - symfony-vendor:/var/www/symfony/vendor
      - /var/www/angular/node_modules
      - /var/www/angular/dist
      - /var/www/angular/.angular

  phpmyadmin:
    environment:
      PMA_USER: root
      PMA_PASSWORD: ${DATABASE_ROOT_PASSWORD}

volumes:
  symfony-vendor:
  symfony-var:
