name: ${PROJECT_NAME}-prod
services:
  symfony:
    image: nginx:latest
    volumes:
      - ./symfony/nginx.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    depends_on:
      php-fpm:
        condition: service_healthy

  php-fpm:
    build:
      context: . # Trick to include both .env and symfony/ in the build context
      dockerfile: ./symfony/Dockerfile
      args:
        PHP_VERSION: ${PHP_VERSION}
      target: php-fpm
    env_file: .env # Vars used both by Docker and Symfony
    environment:
      APP_ENV: prod
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'pidof php-fpm > /dev/null || exit 1']
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      mysql:
        condition: service_healthy
    entrypoint: |
      /bin/bash -c "
        echo '🔄 Applying migrations...'
        php bin/console doctrine:migrations:migrate --no-interaction --allow-no-migration --all-or-nothing --query-time || exit 1
        echo '🚀 Starting PHP-FPM...'
        exec php-fpm
      "

  mysql:
    restart: unless-stopped

  phpmyadmin:
    restart: unless-stopped

volumes:
  mysql-data:
    name: '${PROJECT_NAME}-prod-db'
