name: ${PROJECT_NAME}-dev
services:
  symfony:
    build:
      context: ./symfony
      args:
        PHP_VERSION: ${PHP_VERSION}
        COMPOSER_VERSION: ${COMPOSER_VERSION}
      target: php-symfony
    env_file: .env # Vars used both by Docker and Symfony
    environment:
      APP_ENV: dev
    working_dir: /app/symfony
    volumes:
      - ./:/app
      - symfony-var:/app/symfony/var
      - symfony-vendor:/app/symfony/vendor
      - symfony-jwt:/app/symfony/config/jwt
      - /app/angular/node_modules
      - /app/angular/dist
      - /app/angular/.angular
    depends_on:
      mysql:
        condition: service_healthy

  phpmyadmin:
    environment:
      PMA_USER: root
      PMA_PASSWORD: ${DATABASE_ROOT_PASSWORD}

volumes:
  symfony-jwt:
  symfony-vendor:
  symfony-var:
  mysql-data:
    name: '${PROJECT_NAME}-dev-db'
