services:
  symfony:
    build:
      context: ./symfony
      dockerfile: Dockerfile.nginx
    restart: always
    depends_on:
      php-fpm:
        condition: service_healthy

  php-fpm:
    build:
      context: . # Trick to include both .env and symfony/ in the build context
      dockerfile: ./symfony/Dockerfile
      args:
        PHP_VERSION: ${PHP_VERSION}
      target: php-fpm
    env_file: .env # Vars used both by Docker and Symfony
    restart: always
    healthcheck:
      test: ['CMD-SHELL', 'pidof php-fpm > /dev/null || exit 1']
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    restart: always

  phpmyadmin:
    restart: always
