
# ---------------------------------------------------------------------------- #
#                                     NGINX                                    #
# ---------------------------------------------------------------------------- #
ARG NGINX_VERSION=latest
FROM nginx:${NGINX_VERSION}

WORKDIR /app

COPY . .
RUN mv ./nginx.conf /etc/nginx/conf.d/default.conf

WORKDIR /app