ARG PHP_VERSION

FROM php:${PHP_VERSION}-apache

WORKDIR /var/www

RUN apt-get update &&\
    apt-get install -qq -y --no-install-recommends \
    libpng-dev \
    libonig-dev
RUN apt-get clean &&\
    rm -rf /var/lib/apt/lists/*

# Installer Composer
COPY --from=composer:2.1 /usr/bin/composer /usr/local/bin/composer

# Installer les extensions PHP via install-php-extensions
ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/
RUN chmod +x /usr/local/bin/install-php-extensions &&\
    install-php-extensions \
    pdo_mysql \
    gd \
    opcache \
    zip \
    mbstring \
    a2enmod rewrite

RUN echo "ServerName localhost" >> /etc/apache2/apache2.conf
RUN echo "LogLevel error" >> /etc/apache2/apache2.conf

# Dockerfile should be in the root of the project
COPY --chown=www-data:www-data . .
# Grant privileges for /var/www/
RUN chown -R www-data:www-data . && \
    chmod -R 775 .

RUN mv apache.conf /etc/apache2/sites-enabled &&\
    rm /etc/apache2/sites-enabled/000-default.conf
    # a2ensite default-ssl.conf
    
USER www-data

# todo générer un APP_SECRET
RUN composer install --no-dev --optimize-autoloader
RUN php bin/console cache:warmup --env=prod
RUN composer dump-env prod